/* MG Nihongo – Lerninhalte.
 * Quelle der mit video:true markierten Einträge: „20 Japanisch Vokabeln für deine Japanreise!“
 * (WanderWeib Japan, https://www.youtube.com/watch?v=26VUZNqJ89c). Rest: ergänzte Reise-Basics.
 *
 * Felder: id (= Audiodatei audio/<id>.mp3), cat, jp (Schreibweise), kana (Lesung), romaji, de,
 *         tip (Aussprache-/Nutzungshinweis), who ('staff' = sagt das Personal → männliche Stimme),
 *         tts (abweichender Text für die Sprachausgabe, z. B. Kana statt Kanji für eindeutige Lesung).
 * Wird von index.html, sw.js (importScripts) und tools/gen-audio.py (über node) gelesen.
 */
self.NR_DATA = {
  categories: [
    { id: 'greet',     name: 'Begrüßung & Höflichkeit', emoji: '👋', color: '#FF6B6B' },
    { id: 'transit',   name: 'Unterwegs',               emoji: '🚉', color: '#4D96FF' },
    { id: 'enter',     name: 'Restaurant betreten',     emoji: '🚪', color: '#FFA62B' },
    { id: 'order',     name: 'Bestellen',               emoji: '🍜', color: '#F9844A' },
    { id: 'pay',       name: 'Bezahlen',                emoji: '💴', color: '#43AA8B' },
    { id: 'konbini',   name: 'Konbini & Shopping',      emoji: '🏪', color: '#9D4EDD' },
    { id: 'numbers',   name: 'Zahlen',                  emoji: '🔢', color: '#00B4D8' },
    { id: 'language',  name: 'Verständigung',           emoji: '💬', color: '#F15BB5' },
    { id: 'hotel',     name: 'Hotel',                   emoji: '🏨', color: '#3A86FF' },
    { id: 'emergency', name: 'Notfall & Gesundheit',    emoji: '🆘', color: '#E63946' },
  ],

  phrases: [
    // ── Begrüßung & Höflichkeit ─────────────────────────────────────────────
    { id: 'ohayo', cat: 'greet', video: true, jp: 'おはようございます', kana: 'おはようございます', romaji: 'ohayō gozaimasu', de: 'Guten Morgen',
      tip: 'Das „ō“ lang ziehen. Das „u“ am Ende von „-masu“ ist fast stumm: „gozaimass“.' },
    { id: 'konnichiwa', cat: 'greet', video: true, jp: 'こんにちは', kana: 'こんにちは', romaji: 'konnichiwa', de: 'Guten Tag / Hallo',
      tip: 'Das は am Ende wird hier „wa“ gesprochen. Doppeltes n deutlich halten: „kon-ni-chi-wa“.' },
    { id: 'konbanwa', cat: 'greet', video: true, jp: 'こんばんは', kana: 'こんばんは', romaji: 'konbanwa', de: 'Guten Abend',
      tip: 'Das n vor b klingt fast wie m: „kombanwa“.' },
    { id: 'arigato', cat: 'greet', video: true, jp: 'ありがとうございます', kana: 'ありがとうございます', romaji: 'arigatō gozaimasu', de: 'Vielen Dank',
      tip: 'Das r ist ein kurzes, weiches Zungen-r, zwischen r und l.' },
    { id: 'sumimasen', cat: 'greet', video: true, jp: 'すみません', kana: 'すみません', romaji: 'sumimasen', de: 'Entschuldigung / Verzeihung',
      tip: 'Allzweckwort: Bedienung rufen, sich vorbeidrängeln, sich entschuldigen, sogar als „danke für die Mühe“.' },
    { id: 'hai', cat: 'greet', jp: 'はい', kana: 'はい', romaji: 'hai', de: 'Ja',
      tip: 'Heißt oft auch nur „Ich höre zu“, nicht unbedingt Zustimmung.' },
    { id: 'iie', cat: 'greet', jp: 'いいえ', kana: 'いいえ', romaji: 'iie', de: 'Nein',
      tip: 'Klingt direkt. Höflicher ablehnen: „daijōbu desu“.' },
    { id: 'onegaishimasu', cat: 'greet', video: true, jp: 'お願いします', kana: 'おねがいします', romaji: 'onegaishimasu', de: 'Bitte (höflich, bei einer Bitte)',
      tip: 'Das i in „shi“ ist fast stumm: „onegai-shmass“.' },
    { id: 'kudasai', cat: 'greet', video: true, jp: 'ください', kana: 'ください', romaji: 'kudasai', de: 'Bitte geben Sie mir … (etwas direkter)',
      tip: 'Steht hinter dem Gewünschten: „kore o kudasai“. Etwas weniger höflich als „onegaishimasu“.' },
    { id: 'daijobu', cat: 'greet', video: true, jp: '大丈夫です', kana: 'だいじょうぶです', romaji: 'daijōbu desu', de: 'Alles okay / Nein danke, passt schon',
      tip: 'Die höfliche Art, etwas abzulehnen, z. B. Tüte oder Aufwärmen im Konbini.' },
    { id: 'gomennasai', cat: 'greet', jp: 'ごめんなさい', kana: 'ごめんなさい', romaji: 'gomen nasai', de: 'Es tut mir leid' },
    { id: 'itadakimasu', cat: 'greet', jp: 'いただきます', kana: 'いただきます', romaji: 'itadakimasu', de: 'Guten Appetit (vor dem Essen)',
      tip: 'Sagt man selbst vor dem ersten Bissen, gern mit kurz aneinandergelegten Händen.' },
    { id: 'gochisosama', cat: 'greet', jp: 'ごちそうさまでした', kana: 'ごちそうさまでした', romaji: 'gochisōsama deshita', de: 'Danke für das Essen (nach dem Essen)',
      tip: 'Beim Verlassen des Restaurants Richtung Küche gesagt, das freut jeden Koch.' },
    { id: 'sayonara', cat: 'greet', jp: 'さようなら', kana: 'さようなら', romaji: 'sayōnara', de: 'Auf Wiedersehen (eher endgültig)' },

    // ── Unterwegs ───────────────────────────────────────────────────────────
    { id: 'dokodesuka', cat: 'transit', video: true, jp: 'どこですか', kana: 'どこですか', romaji: 'doko desu ka', de: 'Wo ist …?',
      tip: 'Einfach den Ort davor setzen: „eki wa doko desu ka“. „desu ka“ klingt wie „dess-ka“.' },
    { id: 'toire', cat: 'transit', video: true, jp: 'トイレはどこですか', kana: 'トイレはどこですか', romaji: 'toire wa doko desu ka', de: 'Wo ist die Toilette?' },
    { id: 'eki', cat: 'transit', video: true, jp: '駅', kana: 'えき', romaji: 'eki', de: 'Bahnhof', tts: 'えき' },
    { id: 'sen', cat: 'transit', video: true, jp: '線', kana: 'せん', romaji: 'sen', de: '(Bahn-)Linie', tts: 'せん',
      tip: 'Hinter dem Linien-Namen: Yamanote-sen, Chūō-sen …' },
    { id: 'shinjuku', cat: 'transit', video: true, jp: '新宿駅はどこですか', kana: 'しんじゅくえきはどこですか', romaji: 'Shinjuku-eki wa doko desu ka', de: 'Wo ist der Bahnhof Shinjuku?' },
    { id: 'yamanote', cat: 'transit', video: true, jp: '山手線はどこですか', kana: 'やまのてせんはどこですか', romaji: 'Yamanote-sen wa doko desu ka', de: 'Wo ist die Yamanote-Linie?' },
    { id: 'kippu', cat: 'transit', jp: '切符', kana: 'きっぷ', romaji: 'kippu', de: 'Fahrkarte', tts: 'きっぷ',
      tip: 'Das kleine っ ist eine kurze Pause vor dem p: „kip-pu“.' },
    { id: 'ikimasuka', cat: 'transit', jp: 'この電車は京都に行きますか', kana: 'このでんしゃはきょうとにいきますか', romaji: 'kono densha wa Kyōto ni ikimasu ka', de: 'Fährt dieser Zug nach Kyoto?',
      tip: 'Statt Kyōto jeden Zielort einsetzen.' },
    { id: 'kokoniikitai', cat: 'transit', jp: 'ここに行きたいです', kana: 'ここにいきたいです', romaji: 'koko ni ikitai desu', de: 'Ich möchte hierhin (auf Karte zeigen)',
      tip: 'Perfekt fürs Taxi: Adresse oder Karte zeigen und diesen Satz sagen.' },
    { id: 'deguchi', cat: 'transit', jp: '出口', kana: 'でぐち', romaji: 'deguchi', de: 'Ausgang', tts: 'でぐち' },
    { id: 'iriguchi', cat: 'transit', jp: '入口', kana: 'いりぐち', romaji: 'iriguchi', de: 'Eingang', tts: 'いりぐち' },
    { id: 'migi', cat: 'transit', jp: '右', kana: 'みぎ', romaji: 'migi', de: 'rechts', tts: 'みぎ' },
    { id: 'hidari', cat: 'transit', jp: '左', kana: 'ひだり', romaji: 'hidari', de: 'links', tts: 'ひだり' },
    { id: 'massugu', cat: 'transit', jp: 'まっすぐ', kana: 'まっすぐ', romaji: 'massugu', de: 'geradeaus' },

    // ── Restaurant betreten ─────────────────────────────────────────────────
    { id: 'irasshaimase', cat: 'enter', who: 'staff', jp: 'いらっしゃいませ', kana: 'いらっしゃいませ', romaji: 'irasshaimase', de: 'Herzlich willkommen! (ruft das Personal)',
      tip: 'Darauf antwortet man nicht, ein Nicken reicht.' },
    { id: 'nanmeisama', cat: 'enter', video: true, who: 'staff', jp: '何名様ですか', kana: 'なんめいさまですか', romaji: 'nanmei-sama desu ka', de: 'Wie viele Personen? (fragt das Personal)',
      tip: 'Man kann auch einfach die Anzahl mit den Fingern zeigen.' },
    { id: 'hitori', cat: 'enter', video: true, jp: '一人です', kana: 'ひとりです', romaji: 'hitori desu', de: 'Eine Person', tts: 'ひとりです' },
    { id: 'futari', cat: 'enter', video: true, jp: '二人です', kana: 'ふたりです', romaji: 'futari desu', de: 'Zwei Personen', tts: 'ふたりです' },
    { id: 'sannin', cat: 'enter', video: true, jp: '三人です', kana: 'さんにんです', romaji: 'sannin desu', de: 'Drei Personen', tts: 'さんにんです',
      tip: 'Ab drei Personen einfach Zahl + „nin“: san-nin, yo-nin, go-nin.' },
    { id: 'yonin', cat: 'enter', jp: '四人です', kana: 'よにんです', romaji: 'yonin desu', de: 'Vier Personen', tts: 'よにんです' },
    { id: 'chottomatte', cat: 'enter', video: true, jp: 'ちょっと待ってください', kana: 'ちょっとまってください', romaji: 'chotto matte kudasai', de: 'Einen Moment bitte',
      tip: 'Super nützlich, wenn du noch Geld, Karte oder Suica suchst.' },
    { id: 'mochikaeri_q', cat: 'enter', video: true, who: 'staff', jp: 'お持ち帰りですか', kana: 'おもちかえりですか', romaji: 'o-mochikaeri desu ka', de: 'Zum Mitnehmen? (fragt das Personal)' },
    { id: 'tennai_q', cat: 'enter', video: true, who: 'staff', jp: '店内ですか', kana: 'てんないですか', romaji: 'tennai desu ka', de: 'Hier essen? (fragt das Personal)',
      tip: 'Oft auch länger: „tennai de o-meshiagari desu ka“.' },
    { id: 'tennai_de', cat: 'enter', video: true, jp: '店内でお願いします', kana: 'てんないでおねがいします', romaji: 'tennai de onegaishimasu', de: 'Hier essen, bitte' },
    { id: 'mochikaeri_de', cat: 'enter', video: true, jp: '持ち帰りでお願いします', kana: 'もちかえりでおねがいします', romaji: 'mochikaeri de onegaishimasu', de: 'Zum Mitnehmen, bitte' },

    // ── Bestellen ───────────────────────────────────────────────────────────
    { id: 'chumon', cat: 'order', jp: '注文お願いします', kana: 'ちゅうもんおねがいします', romaji: 'chūmon onegaishimasu', de: 'Ich möchte bestellen',
      tip: 'Vorher „sumimasen!“ rufen oder den Klingelknopf am Tisch drücken.' },
    { id: 'hitotsu', cat: 'order', video: true, jp: '一つ', kana: 'ひとつ', romaji: 'hitotsu', de: 'Eins (ein Stück)', tts: 'ひとつ',
      tip: 'Zum Bestellen von Dingen. „tsu“ klingt wie „ts“ + kurzes u.' },
    { id: 'futatsu', cat: 'order', video: true, jp: '二つ', kana: 'ふたつ', romaji: 'futatsu', de: 'Zwei (Stück)', tts: 'ふたつ' },
    { id: 'mittsu', cat: 'order', video: true, jp: '三つ', kana: 'みっつ', romaji: 'mittsu', de: 'Drei (Stück)', tts: 'みっつ',
      tip: 'Kurze Pause vor dem „tsu“: „mit-tsu“.' },
    { id: 'biru', cat: 'order', video: true, jp: 'ビールをお願いします', kana: 'ビールをおねがいします', romaji: 'bīru o onegaishimasu', de: 'Ein Bier, bitte',
      tip: 'Muster: [Ding] o onegaishimasu. Für mehrere die Anzahl einschieben: „bīru o futatsu onegaishimasu“ = zwei Bier.' },
    { id: 'kore', cat: 'order', video: true, jp: 'これ', kana: 'これ', romaji: 'kore', de: 'Das (hier)',
      tip: 'Auf die Karte oder das Plastik-Essen im Schaufenster zeigen.' },
    { id: 'kore_onegai', cat: 'order', video: true, jp: 'これをお願いします', kana: 'これをおねがいします', romaji: 'kore o onegaishimasu', de: 'Das bitte (höflich)' },
    { id: 'kore_kudasai', cat: 'order', video: true, jp: 'これをください', kana: 'これをください', romaji: 'kore o kudasai', de: 'Das bitte (etwas direkter)' },
    { id: 'osusume_q', cat: 'order', video: true, jp: 'おすすめは何ですか', kana: 'おすすめはなんですか', romaji: 'osusume wa nan desu ka', de: 'Was empfehlen Sie?',
      tip: 'Achtung aus dem Video: Du bekommst, was kommt. Bei Tessa waren es Muscheln 🦪.' },
    { id: 'osusume', cat: 'order', video: true, jp: 'おすすめ', kana: 'おすすめ', romaji: 'osusume', de: 'Empfehlung' },
    { id: 'mizu', cat: 'order', jp: 'お水をください', kana: 'おみずをください', romaji: 'o-mizu o kudasai', de: 'Wasser, bitte',
      tip: 'Leitungswasser/Tee gibt es in Restaurants meist gratis.' },
    { id: 'menyu', cat: 'order', jp: 'メニューをください', kana: 'メニューをください', romaji: 'menyū o kudasai', de: 'Die Speisekarte, bitte' },
    { id: 'eigo_menyu', cat: 'order', jp: '英語のメニューはありますか', kana: 'えいごのメニューはありますか', romaji: 'eigo no menyū wa arimasu ka', de: 'Gibt es eine englische Speisekarte?' },
    { id: 'oishii', cat: 'order', jp: 'おいしいです', kana: 'おいしいです', romaji: 'oishii desu', de: 'Das ist lecker!' },

    // ── Bezahlen ────────────────────────────────────────────────────────────
    { id: 'okaikei', cat: 'pay', video: true, jp: 'すみません、お会計お願いします', kana: 'すみません、おかいけいおねがいします', romaji: 'sumimasen, o-kaikei onegaishimasu', de: 'Entschuldigung, zahlen bitte',
      tip: 'Alternativ: Zeigefinger zu einem ✕ kreuzen. Gezahlt wird meist vorne an der Kasse.' },
    { id: 'ikura', cat: 'pay', jp: 'いくらですか', kana: 'いくらですか', romaji: 'ikura desu ka', de: 'Wie viel kostet das?' },
    { id: 'kado', cat: 'pay', jp: 'カードで払えますか', kana: 'カードではらえますか', romaji: 'kādo de haraemasu ka', de: 'Kann ich mit Karte zahlen?' },
    { id: 'genkin', cat: 'pay', jp: '現金', kana: 'げんきん', romaji: 'genkin', de: 'Bargeld', tts: 'げんきん' },
    { id: 'betsubetsu', cat: 'pay', jp: '別々でお願いします', kana: 'べつべつでおねがいします', romaji: 'betsubetsu de onegaishimasu', de: 'Getrennt zahlen, bitte' },

    // ── Konbini & Shopping ──────────────────────────────────────────────────
    { id: 'fukuro_q', cat: 'konbini', video: true, who: 'staff', jp: '袋いりますか', kana: 'ふくろいりますか', romaji: 'fukuro irimasu ka', de: 'Brauchen Sie eine Tüte? (fragt die Kasse)',
      tip: 'Förmlicher hörst du auch: „fukuro wa go-riyō desu ka?“ – heißt dasselbe.' },
    { id: 'irimasen', cat: 'konbini', video: true, jp: 'いりません', kana: 'いりません', romaji: 'irimasen', de: 'Brauche ich nicht',
      tip: 'Tessas Rettung im Konbini, vorher hat sie jedes Mal eine Tüte bekommen.' },
    { id: 'fukuro_onegai', cat: 'konbini', video: true, jp: '袋お願いします', kana: 'ふくろおねがいします', romaji: 'fukuro onegaishimasu', de: 'Eine Tüte, bitte' },
    { id: 'atatame_q', cat: 'konbini', video: true, who: 'staff', jp: '温めますか', kana: 'あたためますか', romaji: 'atatamemasu ka', de: 'Soll ich es aufwärmen? (fragt die Kasse)',
      tip: 'Kommt beim Kauf von Bentō, Onigiri oder Nudeln.' },
    { id: 'hai_onegai', cat: 'konbini', video: true, jp: 'はい、お願いします', kana: 'はい、おねがいします', romaji: 'hai, onegaishimasu', de: 'Ja, bitte' },
    { id: 'hashi', cat: 'konbini', jp: 'お箸をください', kana: 'おはしをください', romaji: 'o-hashi o kudasai', de: 'Stäbchen, bitte' },
    { id: 'miteirudake', cat: 'konbini', jp: '見ているだけです', kana: 'みているだけです', romaji: 'mite iru dake desu', de: 'Ich schaue nur' },
    { id: 'atm', cat: 'konbini', jp: 'ATMはありますか', kana: 'エーティーエムはありますか', romaji: 'ē-tī-emu wa arimasu ka', de: 'Gibt es hier einen Geldautomaten?',
      tip: 'Fast jeder Konbini (7-Eleven, Lawson, FamilyMart) hat einen, der ausländische Karten nimmt.' },

    // ── Zahlen ──────────────────────────────────────────────────────────────
    { id: 'n1',  cat: 'numbers', jp: '一', kana: 'いち',   romaji: 'ichi', de: '1', tts: 'いち' },
    { id: 'n2',  cat: 'numbers', jp: '二', kana: 'に',     romaji: 'ni',   de: '2', tts: 'に' },
    { id: 'n3',  cat: 'numbers', jp: '三', kana: 'さん',   romaji: 'san',  de: '3', tts: 'さん' },
    { id: 'n4',  cat: 'numbers', jp: '四', kana: 'よん',   romaji: 'yon',  de: '4', tts: 'よん', tip: 'Auch „shi“, aber das klingt wie „Tod“ – daher meist „yon“.' },
    { id: 'n5',  cat: 'numbers', jp: '五', kana: 'ご',     romaji: 'go',   de: '5', tts: 'ご' },
    { id: 'n6',  cat: 'numbers', jp: '六', kana: 'ろく',   romaji: 'roku', de: '6', tts: 'ろく' },
    { id: 'n7',  cat: 'numbers', jp: '七', kana: 'なな',   romaji: 'nana', de: '7', tts: 'なな', tip: 'Auch „shichi“ – „nana“ ist eindeutiger.' },
    { id: 'n8',  cat: 'numbers', jp: '八', kana: 'はち',   romaji: 'hachi', de: '8', tts: 'はち' },
    { id: 'n9',  cat: 'numbers', jp: '九', kana: 'きゅう', romaji: 'kyū',  de: '9', tts: 'きゅう' },
    { id: 'n10', cat: 'numbers', jp: '十', kana: 'じゅう', romaji: 'jū',   de: '10', tts: 'じゅう' },
    { id: 'n100', cat: 'numbers', jp: '百', kana: 'ひゃく', romaji: 'hyaku', de: '100', tts: 'ひゃく' },
    { id: 'n1000', cat: 'numbers', jp: '千', kana: 'せん', romaji: 'sen', de: '1000', tts: 'せん' },
    { id: 'en', cat: 'numbers', jp: '円', kana: 'えん', romaji: 'en', de: 'Yen', tts: 'えん',
      tip: 'Preise: 500円 = go-hyaku en, 1000円 = sen en.' },

    // ── Verständigung ───────────────────────────────────────────────────────
    { id: 'eigo', cat: 'language', video: true, jp: '英語わかりますか', kana: 'えいごわかりますか', romaji: 'eigo wakarimasu ka', de: 'Verstehen Sie Englisch?' },
    { id: 'sukoshi', cat: 'language', video: true, jp: '少し', kana: 'すこし', romaji: 'sukoshi', de: 'Ein bisschen', tts: 'すこし',
      tip: 'Klingt eher wie „skoshi“, das u ist fast stumm.' },
    { id: 'wakarimasen', cat: 'language', jp: 'わかりません', kana: 'わかりません', romaji: 'wakarimasen', de: 'Ich verstehe nicht' },
    { id: 'wakarimashita', cat: 'language', jp: 'わかりました', kana: 'わかりました', romaji: 'wakarimashita', de: 'Verstanden / Alles klar' },
    { id: 'moichido', cat: 'language', jp: 'もう一度お願いします', kana: 'もういちどおねがいします', romaji: 'mō ichido onegaishimasu', de: 'Noch einmal, bitte' },
    { id: 'yukkuri', cat: 'language', jp: 'ゆっくりお願いします', kana: 'ゆっくりおねがいします', romaji: 'yukkuri onegaishimasu', de: 'Langsamer, bitte' },
    { id: 'doitsu', cat: 'language', jp: 'ドイツから来ました', kana: 'ドイツからきました', romaji: 'Doitsu kara kimashita', de: 'Ich komme aus Deutschland' },
    { id: 'nihongo_sukoshi', cat: 'language', jp: '日本語は少しだけです', kana: 'にほんごはすこしだけです', romaji: 'nihongo wa sukoshi dake desu', de: 'Ich spreche nur ein bisschen Japanisch' },
    { id: 'nihongo_jozu', cat: 'language', jp: '日本語はあまり上手じゃありません', kana: 'にほんごはあまりじょうずじゃありません', romaji: 'nihongo wa amari jōzu ja arimasen', de: 'Mein Japanisch ist nicht gut',
      tip: 'Wörtlich „nicht sehr geschickt“ – höflich und bescheiden. Kürzer und genauso üblich: „nihongo ga heta desu“ (日本語が下手です).' },

    // ── Hotel ───────────────────────────────────────────────────────────────
    { id: 'yoyaku', cat: 'hotel', jp: '予約しています', kana: 'よやくしています', romaji: 'yoyaku shite imasu', de: 'Ich habe reserviert',
      tip: 'Danach deinen Namen sagen.' },
    { id: 'checkin', cat: 'hotel', jp: 'チェックインお願いします', kana: 'チェックインおねがいします', romaji: 'chekku-in onegaishimasu', de: 'Einchecken, bitte' },
    { id: 'nimotsu', cat: 'hotel', jp: '荷物を預かってもらえますか', kana: 'にもつをあずかってもらえますか', romaji: 'nimotsu o azukatte moraemasu ka', de: 'Können Sie mein Gepäck aufbewahren?' },
    { id: 'wifi', cat: 'hotel', jp: 'Wi-Fiのパスワードは何ですか', kana: 'ワイファイのパスワードはなんですか', romaji: 'waifai no pasuwādo wa nan desu ka', de: 'Wie lautet das WLAN-Passwort?',
      tts: 'ワイファイのパスワードはなんですか' },

    // ── Notfall & Gesundheit ────────────────────────────────────────────────
    { id: 'tasukete', cat: 'emergency', jp: '助けて！', kana: 'たすけて！', romaji: 'tasukete!', de: 'Hilfe!' },
    { id: 'kyukyusha', cat: 'emergency', jp: '救急車を呼んでください', kana: 'きゅうきゅうしゃをよんでください', romaji: 'kyūkyūsha o yonde kudasai', de: 'Rufen Sie bitte einen Krankenwagen',
      tip: 'Notruf Krankenwagen/Feuerwehr: 119, Polizei: 110.' },
    { id: 'guai', cat: 'emergency', jp: '具合が悪いです', kana: 'ぐあいがわるいです', romaji: 'guai ga warui desu', de: 'Mir geht es nicht gut' },
    { id: 'itai', cat: 'emergency', jp: 'ここが痛いです', kana: 'ここがいたいです', romaji: 'koko ga itai desu', de: 'Hier tut es weh' },
    { id: 'byoin', cat: 'emergency', jp: '病院', kana: 'びょういん', romaji: 'byōin', de: 'Krankenhaus', tts: 'びょういん' },
    { id: 'yakkyoku', cat: 'emergency', jp: '薬局', kana: 'やっきょく', romaji: 'yakkyoku', de: 'Apotheke', tts: 'やっきょく' },
    { id: 'keisatsu', cat: 'emergency', jp: '警察', kana: 'けいさつ', romaji: 'keisatsu', de: 'Polizei', tts: 'けいさつ' },
    { id: 'saifu', cat: 'emergency', jp: '財布をなくしました', kana: 'さいふをなくしました', romaji: 'saifu o nakushimashita', de: 'Ich habe mein Portemonnaie verloren' },
    { id: 'arerugi', cat: 'emergency', jp: 'アレルギーがあります', kana: 'アレルギーがあります', romaji: 'arerugī ga arimasu', de: 'Ich habe eine Allergie' },
    { id: 'nattsu', cat: 'emergency', jp: 'ナッツアレルギーです', kana: 'ナッツアレルギーです', romaji: 'nattsu arerugī desu', de: 'Ich bin allergisch gegen Nüsse' },
    { id: 'niku', cat: 'emergency', jp: '肉は食べられません', kana: 'にくはたべられません', romaji: 'niku wa taberaremasen', de: 'Ich kann kein Fleisch essen' },
  ],

  /* Situations-Dialoge: pro Schritt optional eine Äußerung des Gegenübers (say),
   * dazu eine Situation (prompt), die richtige Antwort (answer) und Ablenker (wrong). */
  dialogs: [
    { id: 'restaurant', title: 'Im Restaurant', emoji: '🍜', color: '#F9844A', steps: [
      { say: 'nanmeisama', prompt: 'Du bist zu zweit unterwegs.', answer: 'futari', wrong: ['futatsu', 'sannin'],
        fb: 'Personen zählt man mit hitori/futari/…-nin, Dinge mit hitotsu/futatsu/…' },
      { prompt: 'Du möchtest die Bedienung rufen.', answer: 'sumimasen', wrong: ['arigato', 'konbanwa'] },
      { prompt: 'Du hättest gern ein Bier.', answer: 'biru', wrong: ['fukuro_onegai', 'okaikei'] },
      { prompt: 'Du weißt nicht, was du essen sollst.', answer: 'osusume_q', wrong: ['ikura', 'dokodesuka'] },
      { prompt: 'Das Essen kommt – bevor du anfängst:', answer: 'itadakimasu', wrong: ['gochisosama', 'ohayo'] },
      { prompt: 'Du bist fertig und möchtest zahlen.', answer: 'okaikei', wrong: ['chumon', 'mizu'] },
      { prompt: 'Beim Hinausgehen bedankst du dich fürs Essen.', answer: 'gochisosama', wrong: ['itadakimasu', 'gomennasai'] },
    ]},
    { id: 'konbini', title: 'An der Konbini-Kasse', emoji: '🏪', color: '#9D4EDD', steps: [
      { say: 'irasshaimase', prompt: 'Du betrittst den Laden und wirst begrüßt. Was tust du?', answer: 'miteirudake', wrong: ['irimasen', 'okaikei'],
        fb: 'Eigentlich antwortet man gar nicht, ein Nicken reicht. Wenn doch, dann passt „Ich schaue nur“.' },
      { say: 'atatame_q', prompt: 'Du hast ein Bentō gekauft und möchtest es warm essen.', answer: 'hai_onegai', wrong: ['irimasen', 'iie'] },
      { say: 'fukuro_q', prompt: 'Du hast deine Stofftasche dabei.', answer: 'irimasen', wrong: ['fukuro_onegai', 'hai_onegai'],
        fb: 'Auch möglich: „daijōbu desu“ – höfliches Nein danke.' },
      { prompt: 'Du brauchst noch Stäbchen.', answer: 'hashi', wrong: ['menyu', 'mizu'] },
      { prompt: 'Du willst wissen, ob Kartenzahlung geht.', answer: 'kado', wrong: ['ikura', 'genkin'] },
      { prompt: 'Du suchst noch deine Karte im Geldbeutel.', answer: 'chottomatte', wrong: ['gomennasai', 'wakarimasen'] },
      { prompt: 'Zum Abschied:', answer: 'arigato', wrong: ['konbanwa', 'itadakimasu'] },
    ]},
    { id: 'imbiss', title: 'Imbiss & Café', emoji: '☕', color: '#FFA62B', steps: [
      { say: 'irasshaimase', prompt: 'Du stehst an der Theke und zeigst auf ein Bild auf der Karte.', answer: 'kore_onegai', wrong: ['kore', 'doitsu'],
        fb: '„kore“ allein ist okay, mit „o onegaishimasu“ wird es ein höflicher Satz.' },
      { say: 'mochikaeri_q', prompt: 'Du willst im Laden essen.', answer: 'tennai_de', wrong: ['mochikaeri_de', 'irimasen'] },
      { say: 'tennai_q', prompt: 'Du willst es mitnehmen.', answer: 'mochikaeri_de', wrong: ['tennai_de', 'yoyaku'] },
      { prompt: 'Du willst den Preis wissen.', answer: 'ikura', wrong: ['eigo', 'nanmeisama'] },
      { prompt: 'Die Antwort war dir zu schnell.', answer: 'yukkuri', wrong: ['wakarimashita', 'arigato'] },
    ]},
    { id: 'bahnhof', title: 'Am Bahnhof', emoji: '🚉', color: '#4D96FF', steps: [
      { prompt: 'Du suchst den Bahnhof Shinjuku.', answer: 'shinjuku', wrong: ['yamanote', 'toire'] },
      { prompt: 'Du willst wissen, ob dieser Zug nach Kyoto fährt.', answer: 'ikimasuka', wrong: ['kokoniikitai', 'kippu'] },
      { prompt: 'Welches Schild führt dich hinaus?', answer: 'deguchi', wrong: ['iriguchi', 'eki'] },
      { prompt: 'Du fragst, ob jemand Englisch versteht.', answer: 'eigo', wrong: ['doitsu', 'wakarimasen'] },
      { say: 'sukoshi', prompt: 'Die Person hat dir geholfen.', answer: 'arigato', wrong: ['sumimasen', 'sayonara'],
        fb: '„sumimasen“ geht auch als Dank für Mühe – „arigatō gozaimasu“ ist hier am klarsten.' },
    ]},
    { id: 'hotel', title: 'Im Hotel', emoji: '🏨', color: '#3A86FF', steps: [
      { say: 'irasshaimase', prompt: 'Du kommst an der Rezeption an.', answer: 'yoyaku', wrong: ['chumon', 'miteirudake'] },
      { prompt: 'Das Zimmer ist noch nicht fertig – dein Koffer soll bleiben.', answer: 'nimotsu', wrong: ['saifu', 'hashi'] },
      { prompt: 'Du brauchst das WLAN-Passwort.', answer: 'wifi', wrong: ['eigo_menyu', 'ikura'] },
      { prompt: 'Du hast es verstanden.', answer: 'wakarimashita', wrong: ['wakarimasen', 'moichido'] },
    ]},
    { id: 'notfall', title: 'Notfall & Apotheke', emoji: '🆘', color: '#E63946', steps: [
      { prompt: 'Dir geht es plötzlich schlecht.', answer: 'guai', wrong: ['oishii', 'daijobu'] },
      { prompt: 'Du zeigst auf deinen Bauch.', answer: 'itai', wrong: ['kore', 'massugu'] },
      { prompt: 'Du suchst eine Apotheke.', answer: 'yakkyoku', wrong: ['byoin', 'keisatsu'] },
      { prompt: 'Im Restaurant: Du verträgst keine Nüsse.', answer: 'nattsu', wrong: ['niku', 'oishii'] },
      { prompt: 'Es ist ernst – jemand braucht einen Krankenwagen.', answer: 'kyukyusha', wrong: ['tasukete', 'keisatsu'],
        fb: '„tasukete!“ ruft um Hilfe – den Krankenwagen holt der ganze Satz. Notruf: 119.' },
    ]},
  ],
};
